### ISSUE TITLE
Forcing always to do a warm start

### ISSUE THREAD

**Issue by oxinabox** [LilithHafner/Chairmarks.jl#129]
It seems like if something is longer than a particular threshold then `@b` runs it only once.
I never want to see compilation time
So I always want it run at least twice

**Comment by LilithHafner** [comment]
You correctly identified that charimarks sometimes omits a warmup. There's a wee bit of explanation at https://chairmarks.lilithhafner.com/stable/explanations.

For the most part, if the runtime budget (default 0.1 seconds) is exceeded in the first trial, then we'll stop there (i.e. no warmup). However, it that trial was mostly compile time, then we run a second trial regardless of the runtime. For example

```julia-repl
julia> objects = [getproperty(Base, s) for s in names(Base, all=true) if isdefined(Base, s)];

julia> funcs = [f for f in objects if Base.return_types(f, Tuple{Float64}) == [Float64] && Base.infer_effects(f, Tuple{Float64}).nothrow];

julia> g(x) = [sort(x, by=f) for f in funcs]
g (generic function with 1 method)

julia> @time @eval @b [1.0, 2.0, 3.0] g
  6.694453 seconds (19.37 M allocations: 973.922 MiB, 2.13% gc time, 98.49% compilation time)
61.291 μs (365 allocs: 11.750 KiB)

julia> @time @eval @b 1 sleep
  1.048317 seconds (34.81 k allocations: 1.741 MiB, 4.36% compilation time)
1.002 s (4 allocs: 112 bytes, without a warmup)
```

Right now the heuristic for skipping the warmup is "does the runtime exceed twice the budget _and_ no more than half of that time was spent compiling". So anything with a runtime (excluding compile time) less than the benchmarking runtime budget should get a warmup.

https://github.com/LilithHafner/Chairmarks.jl/blob/ac3f23b53b964fb548a931cd81d12490ac27a097/src/benchmarking.jl#L56-L60

Would this be acceptable for your use case if it were better documented or do you still want a behavior change?

**Comment by oxinabox** [comment]
I think i do want a flag.
Often personally, I just don't care how long my benchmark takes as long as its fair.
because i am benchmarking a bunch of different implementations to compare them.
And it isn't fair if some include compile time and others don't.
Which I guess is happening because we are right on that boundary as my stuff did all take between 0.3 and 2.3 seconds to run

**Comment by LilithHafner** [comment]
> I just don't care how long my benchmark takes

Would you want to set your default runtime budget to something higher than 0.1 seconds with #121? Then no matter how much (or little) compile time there is, as long as the runtime of the function is less than your budget you'll get a warmup.

> as long as its fair

Would #53 be the best solution here? That way they would all have the same warmup status and also all have the same number of evals.

---

I'm willing to add a `force_warmup` keyword argument with default value of `Chairmarks.DEFAULTS.force_warmup` which defaults to `false`, but I want to make sure that that would 
a) actually solve your problem, and
b) there isn't already a better way in the works

**Comment by oxinabox** [comment]
yes #53 would do nicely.
and #121 would be a good work around
