### ISSUE TITLE
Will this be registered?

### ISSUE THREAD

**Issue by gdalle** [LilithHafner/Chairmarks.jl#6]
Hi Lilith!
I'm updating my blog Modern Julia Workflows and I'm wondering if I should include this among the benchmarking tools, or if it's still a prototype mainly for yourself?
Thanks

**Comment by LilithHafner** [comment]
It's already registered and I use it for most of my benchmarking needs. Functionality-wise, I think it's ready for wider use, though it still needs docs.

**Comment by gdalle** [comment]
Thanks! I only asked because I didn't see any release on the GitHub repo or stable docs, that's usually my quick way of checking registration instead of installing the package

**Comment by LilithHafner** [comment]
Ah, yes. That is probably due to tagbot being broken. I'll look into it.

**Comment by LilithHafner** [comment]
Fixed! Thanks for reporting.
