### ISSUE TITLE
Samples parameters is off by one?

### ISSUE THREAD

**Issue by gdalle** [LilithHafner/Chairmarks.jl#91]
```julia
julia> @be sleep(0.01) evals=1 samples=1
Benchmark: 0 samples

julia> @be sleep(0.01) evals=1 samples=2
Benchmark: 1 sample with 1 evaluation
       11.362 ms (4 allocs: 112 bytes)
```

**Comment by gdalle** [comment]
Could it be because of this line, where the inequality should be large?

https://github.com/LilithHafner/Chairmarks.jl/blob/5aa41f9d4df13120f5d1cfba2fc210e8f3fcafc8/src/benchmarking.jl#L101

**Comment by LilithHafner** [comment]
Thanks for reporting! That's almost the right fix, but there is actually another sample generated above, so it's the `resize!(..., i-1)` below that discards a sample. See #92 for more info
